# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches: 
    include:
    - master-faultinjector

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployFI
  steps:
  - bash: echo "Starting"
  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: 'daweins''s Azure(82e247ea-1d53-46d8-8ea4-374aa9dd4ae5)'
      appType: 'functionApp'
      appName: 'daweinsgroverfi'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      deploymentMethod: 'auto'

